### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by andresriancho** [franela/vault#16]
> Installing
> You need sure the copy the correct binary into your PATH and to have GPG installed.

That might be not enough for someone wanting to test the software in 5 mins. For us python people it's not trivial to understand these go projects ;)

**Comment by marcosnils** [comment]
@andresriancho thanks for the feedback. It's not necessary to understand Go in order to install the project. The flow for a new user would be as follow:

- Download the binary file from your distribution (click on the distro icon in the readme file) and place it in your PATH
- Make sure you have GPG installed (Vault also performs this validation as well)
- Enjoy!

Is there a way you might think we can simplify this process?.

**Comment by andresriancho** [comment]
Ah! Never saw that first line telling me to download the binary. I might have been confused by the big icons.

Playing devil's advocate here, I trust you and I'll run a binary that comes from you but... what about the rest of the world? Maybe build instructions might be a good idea, so people can read the source and build the binaries themselves.

**Comment by marcosnils** [comment]
@andresriancho good idea. A makefile is already provided to build binary files. I guess it's just a matter of updating the README file with instructions. Do you think of a way to provide our users the binaries in a way they can trust them?. I.E: If we make them available through our CI server. In that way users can see where that binary came from. 

We can also generate an MD5 in our build process so users can validate this as well.

**Comment by xetorthio** [comment]
I guess the fear is that if it is already compiled, so users don't know what they are running unless they compile it themselves. I don't think md5 checksums, etc, avoid that situation in any way.
