### ISSUE TITLE
Exit code 2 on value set

### ISSUE THREAD

**Issue by andresriancho** [franela/vault#20]
Vault looks like:
```
⌂63% [pablo:/tmp/foo] $ cat Vaultfile 
{"Recipients":[{"Name":"andres","Fingerprint":"99010C0E0C44AA90B6D6D2412D32F868AA4D8C80"}]}⌂63% [pablo:/tmp/foo] $
```

Set command:
```
⌂63% [pablo:/tmp/foo] 130 $ ./vault set . lala
exit status 2[pablo:/tmp/foo] 1 
```

Several issues:
 * Set doesn't work
 * Missing `\n` after `exit status 2`
 * Error should help the user

**Comment by marcosnils** [comment]
@andresriancho try running `vault --verbose set . lala`

**Comment by andresriancho** [comment]
Verbose mode helps, but as a regular user that doesn't want to google or invest time it's still difficult to continue:

```
exit status 2[pablo:/tmp/foo] 1 $ ./vault --verbose set . lala
2015/10/19 18:08:39 Running: gpg --encrypt --armor --batch --yes --output /tmp/foo/..asc --recipient 99010C0E0C44AA90B6D6D2412D32F868AA4D8C80
2015/10/19 18:08:39 Running: /usr/bin/gpg gpg --encrypt --armor --batch --yes --output /tmp/foo/..asc --recipient 99010C0E0C44AA90B6D6D2412D32F868AA4D8C80
2015/10/19 18:08:39 gpg: 5A26C376: There is no assurance this key belongs to the named user
2015/10/19 18:08:39 gpg: [stdin]: encryption failed: unusable public key
exit status 22015/10/19 18:08:39 Running: /usr/bin/gpg gpg --list-secret-keys --with-colons
[pablo:/tmp/foo] 1 $ 
```

**Comment by marcosnils** [comment]
@andresriancho totally agree. This issue  is related to something that will be fixed with #7. I'm closing this as it's covered by the other issue.

**Comment by andresriancho** [comment]
So, how do I fix this in my install? Is a new release pending? Should I build a new binary from source to get this changes?

**Comment by marcosnils** [comment]
@andresriancho the reason is because you don't trust in the key which you want to encrypt data to. You just need to do `gpg --sign-key <fingerprint>` to sign a users key. 

In the latest vault version (which is not released yet) when you execute `vault recipients` you'll get a colored output showing which recipients are trusted and which don't. You can check the README file for an example. 

If you want this feature you'll have to build vault from source. For that, make sure you have Go installed and execute `make install && make build`
